import type { SplitPlan } from "../types/split";

interface SplitExportCardProps {
  plan: SplitPlan;
  userName: string;
}

/** Off-screen branded card captured to PNG by html-to-image (see
 * SplitGeneratorPage's handleExport). Fixed dark/violet styling regardless
 * of the viewer's current theme — this is a shareable brand asset, not a
 * themed UI surface, so it should look the same every time it's exported. */
export default function SplitExportCard({ plan, userName }: SplitExportCardProps) {
  return (
    <div
      style={{
        width: 800,
        padding: 40,
        background: "#0a0a0a",
        color: "#f5f5f5",
        fontFamily: "Arial, Helvetica, sans-serif",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 28 }}>
        <div style={{ fontSize: 22, fontWeight: 700 }}>
          Lift<span style={{ color: "#8b5cf6" }}>Ryt</span> AI
        </div>
        <div style={{ fontSize: 12, color: "#737373" }}>{userName}'s training split</div>
      </div>

      <div style={{ marginBottom: 24 }}>
        <div style={{ fontSize: 28, fontWeight: 700 }}>{plan.split_type}</div>
        <div style={{ fontSize: 13, color: "#a3a3a3", marginTop: 4 }}>
          {plan.days_per_week} days/week &middot; {plan.goal.replace("_", " ")} &middot;{" "}
          {plan.experience_level}
        </div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
        {plan.days.map((day) => (
          <div key={day.day_number} style={{ borderTop: "1px solid #262626", paddingTop: 16 }}>
            <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 10 }}>
              Day {day.day_number}: {day.label}
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {day.exercises.map((ex) => (
                <div
                  key={ex.exercise_id}
                  style={{ display: "flex", justifyContent: "space-between", fontSize: 14 }}
                >
                  <span>{ex.name}</span>
                  <span style={{ color: "#a3a3a3" }}>
                    {ex.sets}&times;{ex.reps}
                  </span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <div
        style={{
          marginTop: 32,
          paddingTop: 16,
          borderTop: "1px solid #262626",
          fontSize: 11,
          color: "#737373",
          textAlign: "center",
        }}
      >
        Rule-based, not AI-guessed. Generated by LiftRyt AI.
      </div>
    </div>
  );
}
