"""Seed data for the exercise library.

Each row's shape matches app.models.exercise.Exercise's column names so the
seed script can pass a row straight into an insert/upsert without
translation. Muscle names use a fixed, lowercase, underscore-separated
vocabulary (chest, lats, quads, ...) — kept consistent across every row so
the /exercises/muscles filter dropdown and the array-overlap muscle filter
both work correctly.
"""

EXERCISES: list[dict] = [
    # ---- Push: chest / shoulders / triceps ----
    {
        "name": "Barbell Bench Press",
        "description": "Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower it to mid-chest with control, then press back up to lockout. The foundational horizontal push.",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["front_delts", "triceps"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Incline Barbell Bench Press",
        "description": "Bench press on a 30-45 degree incline to bias the upper chest and front delts. Lower to the upper chest, not the neck.",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["front_delts", "triceps"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "intermediate",
    },
    {
        "name": "Dumbbell Bench Press",
        "description": "Press dumbbells from chest level to lockout on a flat bench. Greater range of motion and unilateral stability demand than the barbell version.",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["front_delts", "triceps"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Incline Dumbbell Press",
        "description": "Dumbbell press on an incline bench, targeting the upper chest with a deeper stretch at the bottom than the barbell incline allows.",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["front_delts", "triceps"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "intermediate",
    },
    {
        "name": "Overhead Press",
        "description": "Standing barbell press from shoulder height to overhead lockout, bracing the core and glutes to keep the torso upright. The standard test of raw shoulder strength.",
        "primary_muscles": ["front_delts"],
        "secondary_muscles": ["side_delts", "triceps", "abs"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "intermediate",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "description": "Seated or standing dumbbell press overhead. Allows a more natural wrist/shoulder path than a fixed barbell.",
        "primary_muscles": ["front_delts"],
        "secondary_muscles": ["side_delts", "triceps"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Arnold Press",
        "description": "Dumbbell press that rotates from a palms-in bottom position to palms-out lockout, adding side-delt recruitment through the rotation.",
        "primary_muscles": ["front_delts", "side_delts"],
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "intermediate",
    },
    {
        "name": "Push-Up",
        "description": "Bodyweight horizontal press from a plank position. Keep the body in a straight line from head to heels throughout.",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["front_delts", "triceps", "abs"],
        "equipment": "bodyweight",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Dip",
        "description": "Lower the body between parallel bars until the shoulders are below the elbows, then press back up. Leaning forward biases chest; staying upright biases triceps.",
        "primary_muscles": ["chest", "triceps"],
        "secondary_muscles": ["front_delts"],
        "equipment": "bodyweight",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "intermediate",
    },
    {
        "name": "Cable Fly",
        "description": "Standing cable crossover bringing both handles together in front of the chest with a slight elbow bend throughout. Isolates the chest through horizontal adduction.",
        "primary_muscles": ["chest"],
        "secondary_muscles": ["front_delts"],
        "equipment": "cable",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Pec Deck",
        "description": "Machine chest fly performed seated, bringing the arms together in front of the chest. Very stable, easy to isolate the pecs safely.",
        "primary_muscles": ["chest"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Lateral Raise",
        "description": "Raise dumbbells out to the sides to shoulder height, leading with the elbows. The primary side-delt (shoulder width) builder.",
        "primary_muscles": ["side_delts"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Cable Lateral Raise",
        "description": "Lateral raise performed on a low cable pulley, keeping constant tension on the side delt through the entire range, unlike dumbbells at the top.",
        "primary_muscles": ["side_delts"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "intermediate",
    },
    {
        "name": "Front Raise",
        "description": "Raise a dumbbell or plate straight in front of the body to shoulder height. Targets the front delts directly.",
        "primary_muscles": ["front_delts"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Rear Delt Fly",
        "description": "Bent-over or machine fly raising the arms out to the sides to target the rear delts, the most commonly under-trained delt head.",
        "primary_muscles": ["rear_delts"],
        "secondary_muscles": ["upper_back"],
        "equipment": "dumbbell",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Tricep Pushdown",
        "description": "Cable pushdown with a straight bar or rope, elbows pinned to the sides, extending the forearms down to lockout.",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Overhead Tricep Extension",
        "description": "Extend a dumbbell or EZ-bar from behind the head to lockout overhead. Emphasizes the long head of the triceps due to the shoulder-flexed position.",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "beginner",
    },
    {
        "name": "Close-Grip Bench Press",
        "description": "Bench press with a shoulder-width or narrower grip, keeping elbows tucked to shift emphasis from chest to triceps.",
        "primary_muscles": ["triceps"],
        "secondary_muscles": ["chest", "front_delts"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "push",
        "difficulty": "intermediate",
    },
    {
        "name": "Skull Crusher",
        "description": "Lying EZ-bar extension lowering the bar toward the forehead, then extending back to lockout. Keep the upper arms stationary.",
        "primary_muscles": ["triceps"],
        "secondary_muscles": [],
        "equipment": "ez_bar",
        "movement_type": "isolation",
        "category": "push",
        "difficulty": "intermediate",
    },
    # ---- Pull: back / biceps ----
    {
        "name": "Deadlift",
        "description": "Hip-hinge from the floor to full hip and knee extension, bar traveling close to the shins and thighs. The most complete posterior-chain compound lift.",
        "primary_muscles": ["lower_back", "hamstrings", "glutes"],
        "secondary_muscles": ["lats", "traps", "forearms"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "intermediate",
    },
    {
        "name": "Rack Pull",
        "description": "Partial deadlift starting from pins set just below knee height, allowing heavier loading of the top-range lockout and upper back.",
        "primary_muscles": ["lower_back", "traps"],
        "secondary_muscles": ["lats", "glutes", "forearms"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "advanced",
    },
    {
        "name": "Barbell Row",
        "description": "Bent-over row pulling the bar to the lower chest/upper abdomen, torso held near-parallel to the floor. Core back-thickness builder.",
        "primary_muscles": ["lats", "upper_back"],
        "secondary_muscles": ["biceps", "rear_delts"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "intermediate",
    },
    {
        "name": "Pendlay Row",
        "description": "Barbell row starting each rep from a dead stop on the floor with a flat back, emphasizing explosive upper-back power.",
        "primary_muscles": ["upper_back", "lats"],
        "secondary_muscles": ["biceps", "rear_delts"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "advanced",
    },
    {
        "name": "Dumbbell Row",
        "description": "Single-arm row supported by a bench, pulling the dumbbell to the hip. Allows a longer stretch and unilateral focus.",
        "primary_muscles": ["lats"],
        "secondary_muscles": ["biceps", "upper_back", "rear_delts"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "T-Bar Row",
        "description": "Chest-supported or landmine row pulling a loaded bar to the torso. Comfortable on the lower back while still loading heavy.",
        "primary_muscles": ["lats", "upper_back"],
        "secondary_muscles": ["biceps", "rear_delts"],
        "equipment": "machine",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "intermediate",
    },
    {
        "name": "Seated Cable Row",
        "description": "Seated row pulling a handle to the torso with a neutral spine, squeezing the shoulder blades together at the finish.",
        "primary_muscles": ["upper_back", "lats"],
        "secondary_muscles": ["biceps", "rear_delts"],
        "equipment": "cable",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "Lat Pulldown",
        "description": "Pull a cable bar down to the upper chest from an overhead position, driving the elbows down and back. A pull-up regression that lets you scale the load.",
        "primary_muscles": ["lats"],
        "secondary_muscles": ["biceps", "upper_back"],
        "equipment": "cable",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "Pull-Up",
        "description": "Hang from a bar with an overhand grip and pull the chin above it. The bodyweight benchmark for back and grip strength.",
        "primary_muscles": ["lats"],
        "secondary_muscles": ["biceps", "upper_back", "forearms"],
        "equipment": "bodyweight",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "intermediate",
    },
    {
        "name": "Chin-Up",
        "description": "Pull-up variation with an underhand grip, shifting more emphasis onto the biceps while still heavily training the lats.",
        "primary_muscles": ["lats", "biceps"],
        "secondary_muscles": ["upper_back", "forearms"],
        "equipment": "bodyweight",
        "movement_type": "compound",
        "category": "pull",
        "difficulty": "intermediate",
    },
    {
        "name": "Face Pull",
        "description": "Cable pull to the face with high elbows, externally rotating the shoulders at the finish. Excellent for rear delts and shoulder health.",
        "primary_muscles": ["rear_delts"],
        "secondary_muscles": ["upper_back", "traps"],
        "equipment": "cable",
        "movement_type": "isolation",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "Barbell Curl",
        "description": "Standing curl from a straight or EZ-bar, elbows fixed at the sides. The classic biceps mass builder.",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment": "barbell",
        "movement_type": "isolation",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "Dumbbell Curl",
        "description": "Standing or seated alternating dumbbell curl, optionally supinating the wrist through the range for extra peak contraction.",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment": "dumbbell",
        "movement_type": "isolation",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "Hammer Curl",
        "description": "Neutral-grip dumbbell curl that emphasizes the brachialis and forearm alongside the biceps.",
        "primary_muscles": ["biceps", "forearms"],
        "secondary_muscles": [],
        "equipment": "dumbbell",
        "movement_type": "isolation",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "Preacher Curl",
        "description": "Curl performed with the upper arms braced against an angled pad, removing shoulder momentum and isolating the biceps hard.",
        "primary_muscles": ["biceps"],
        "secondary_muscles": [],
        "equipment": "ez_bar",
        "movement_type": "isolation",
        "category": "pull",
        "difficulty": "intermediate",
    },
    {
        "name": "Cable Curl",
        "description": "Curl performed on a low cable, keeping constant tension on the biceps through the top of the rep where dumbbells go slack.",
        "primary_muscles": ["biceps"],
        "secondary_muscles": ["forearms"],
        "equipment": "cable",
        "movement_type": "isolation",
        "category": "pull",
        "difficulty": "beginner",
    },
    {
        "name": "Barbell Shrug",
        "description": "Elevate the shoulders straight up while holding a loaded barbell, pausing briefly at the top. Direct trap builder.",
        "primary_muscles": ["traps"],
        "secondary_muscles": ["forearms"],
        "equipment": "barbell",
        "movement_type": "isolation",
        "category": "pull",
        "difficulty": "beginner",
    },
    # ---- Legs ----
    {
        "name": "Back Squat",
        "description": "Barbell on the upper back, squat to at least parallel and drive back up. The primary lower-body compound lift.",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "lower_back", "abs"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "intermediate",
    },
    {
        "name": "Front Squat",
        "description": "Barbell racked across the front delts, squatting with a more upright torso than a back squat, biasing the quads further.",
        "primary_muscles": ["quads"],
        "secondary_muscles": ["glutes", "abs"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "advanced",
    },
    {
        "name": "Goblet Squat",
        "description": "Squat holding a single dumbbell or kettlebell at chest height. A beginner-friendly way to learn squat mechanics.",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["abs"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "beginner",
    },
    {
        "name": "Hack Squat",
        "description": "Machine squat on an angled sled, allowing heavy quad-focused loading with less lower-back demand than a free squat.",
        "primary_muscles": ["quads"],
        "secondary_muscles": ["glutes"],
        "equipment": "machine",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "intermediate",
    },
    {
        "name": "Leg Press",
        "description": "Press a weighted sled away from the body on a fixed track. Loads the quads and glutes with minimal spinal loading.",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment": "machine",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "beginner",
    },
    {
        "name": "Romanian Deadlift",
        "description": "Hip hinge with a slight knee bend, lowering the bar along the thighs until a deep hamstring stretch is felt, then driving the hips forward.",
        "primary_muscles": ["hamstrings", "glutes"],
        "secondary_muscles": ["lower_back"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "intermediate",
    },
    {
        "name": "Good Morning",
        "description": "Bar on the back, hinge at the hips with a soft knee bend until the torso is near parallel, then return to standing. Loads the posterior chain like an RDL with a different bar position.",
        "primary_muscles": ["hamstrings", "lower_back"],
        "secondary_muscles": ["glutes"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "advanced",
    },
    {
        "name": "Leg Curl",
        "description": "Machine curl flexing the knee against resistance, lying or seated. Direct hamstring isolation.",
        "primary_muscles": ["hamstrings"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_type": "isolation",
        "category": "legs",
        "difficulty": "beginner",
    },
    {
        "name": "Leg Extension",
        "description": "Machine extension straightening the knee against resistance. Direct quad isolation, useful for finishing volume.",
        "primary_muscles": ["quads"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_type": "isolation",
        "category": "legs",
        "difficulty": "beginner",
    },
    {
        "name": "Walking Lunge",
        "description": "Alternating forward lunges covering distance, holding dumbbells or a barbell. Trains quads and glutes unilaterally with a balance/stability demand.",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings", "abs"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "intermediate",
    },
    {
        "name": "Bulgarian Split Squat",
        "description": "Rear-foot-elevated single-leg squat. Heavily loads the front leg's quad and glute with a large stretch under load.",
        "primary_muscles": ["quads", "glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "intermediate",
    },
    {
        "name": "Hip Thrust",
        "description": "Shoulders on a bench, barbell across the hips, drive the hips up to full extension. The most direct glute-loading compound movement.",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "legs",
        "difficulty": "beginner",
    },
    {
        "name": "Glute Bridge",
        "description": "Bodyweight or loaded hip extension performed lying on the floor. A regression of the hip thrust, still an effective glute builder.",
        "primary_muscles": ["glutes"],
        "secondary_muscles": ["hamstrings"],
        "equipment": "bodyweight",
        "movement_type": "isolation",
        "category": "legs",
        "difficulty": "beginner",
    },
    {
        "name": "Standing Calf Raise",
        "description": "Rise onto the toes against resistance with the knee straight, pausing at full stretch and full contraction. Targets the gastrocnemius.",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_type": "isolation",
        "category": "legs",
        "difficulty": "beginner",
    },
    {
        "name": "Seated Calf Raise",
        "description": "Calf raise performed with the knee bent, shifting emphasis to the soleus rather than the gastrocnemius.",
        "primary_muscles": ["calves"],
        "secondary_muscles": [],
        "equipment": "machine",
        "movement_type": "isolation",
        "category": "legs",
        "difficulty": "beginner",
    },
    # ---- Core ----
    {
        "name": "Plank",
        "description": "Hold a straight-body position supported on forearms and toes, bracing the abs and glutes. Anti-extension core stability.",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["obliques"],
        "equipment": "bodyweight",
        "movement_type": "isolation",
        "category": "core",
        "difficulty": "beginner",
    },
    {
        "name": "Hanging Leg Raise",
        "description": "Hang from a bar and raise the legs to hip height or higher without swinging. A demanding lower-abs and hip-flexor movement.",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["hip_flexors"],
        "equipment": "bodyweight",
        "movement_type": "isolation",
        "category": "core",
        "difficulty": "advanced",
    },
    {
        "name": "Cable Crunch",
        "description": "Kneeling crunch against a cable, flexing the spine against resistance. Allows progressive overload on a crunch pattern.",
        "primary_muscles": ["abs"],
        "secondary_muscles": [],
        "equipment": "cable",
        "movement_type": "isolation",
        "category": "core",
        "difficulty": "beginner",
    },
    {
        "name": "Ab Wheel Rollout",
        "description": "Roll a wheel out from a kneeling position, keeping the spine neutral, then pull back to start. A demanding anti-extension exercise.",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["obliques", "lats"],
        "equipment": "bodyweight",
        "movement_type": "isolation",
        "category": "core",
        "difficulty": "advanced",
    },
    {
        "name": "Russian Twist",
        "description": "Seated rotational twist, optionally holding a weight, touching it to the floor on each side. Trains rotational core strength.",
        "primary_muscles": ["obliques"],
        "secondary_muscles": ["abs"],
        "equipment": "bodyweight",
        "movement_type": "isolation",
        "category": "core",
        "difficulty": "beginner",
    },
    {
        "name": "Sit-Up",
        "description": "Full spinal flexion from lying to seated. A classic ab movement, though less spine-friendly than crunch variations.",
        "primary_muscles": ["abs"],
        "secondary_muscles": ["hip_flexors"],
        "equipment": "bodyweight",
        "movement_type": "isolation",
        "category": "core",
        "difficulty": "beginner",
    },
    {
        "name": "Cable Woodchopper",
        "description": "Diagonal cable pull from high to low (or low to high) across the body, rotating through the torso. Trains rotational and anti-rotational core strength.",
        "primary_muscles": ["obliques"],
        "secondary_muscles": ["abs"],
        "equipment": "cable",
        "movement_type": "isolation",
        "category": "core",
        "difficulty": "intermediate",
    },
    # ---- Full body ----
    {
        "name": "Kettlebell Swing",
        "description": "Hip-hinge ballistic movement driving a kettlebell to chest/eye height using hip extension, not the arms. Builds explosive posterior-chain power and conditioning.",
        "primary_muscles": ["glutes", "hamstrings"],
        "secondary_muscles": ["lower_back", "abs", "forearms"],
        "equipment": "kettlebell",
        "movement_type": "compound",
        "category": "full_body",
        "difficulty": "intermediate",
    },
    {
        "name": "Farmer's Carry",
        "description": "Walk for distance or time holding a heavy dumbbell or kettlebell in each hand. Builds grip, traps, and total-body bracing strength.",
        "primary_muscles": ["forearms", "traps"],
        "secondary_muscles": ["abs", "quads"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "full_body",
        "difficulty": "beginner",
    },
    {
        "name": "Turkish Get-Up",
        "description": "A multi-step sequence from lying to standing while keeping a loaded kettlebell locked out overhead. Builds shoulder stability, core strength, and full-body coordination.",
        "primary_muscles": ["abs", "side_delts"],
        "secondary_muscles": ["glutes", "quads", "triceps"],
        "equipment": "kettlebell",
        "movement_type": "compound",
        "category": "full_body",
        "difficulty": "advanced",
    },
    {
        "name": "Barbell Clean and Press",
        "description": "Pull a barbell from the floor to the shoulders in one motion, then press it overhead. A demanding full-body power movement borrowed from Olympic weightlifting.",
        "primary_muscles": ["quads", "glutes", "front_delts"],
        "secondary_muscles": ["traps", "triceps", "hamstrings"],
        "equipment": "barbell",
        "movement_type": "compound",
        "category": "full_body",
        "difficulty": "advanced",
    },
    {
        "name": "Renegade Row",
        "description": "Alternating dumbbell row performed from a push-up plank position, forcing heavy anti-rotation bracing while rowing each side.",
        "primary_muscles": ["lats", "abs"],
        "secondary_muscles": ["front_delts", "triceps", "obliques"],
        "equipment": "dumbbell",
        "movement_type": "compound",
        "category": "full_body",
        "difficulty": "advanced",
    },
]
