"""add google_avatar_url to users

Revision ID: 1292668f3937
Revises: 29314511ddfb
Create Date: 2026-08-09 14:13:04.034836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1292668f3937'
down_revision: Union[str, None] = '29314511ddfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_avatar_url', sa.String(length=1024), nullable=True))
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_avatar_url')
    # ### end Alembic commands ###
