"""init schema

Revision ID: 1ede5e6ec696
Revises: 
Create Date: 2026-08-06 15:42:04.948653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ede5e6ec696'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_muscles', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('secondary_muscles', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=False),
    sa.Column('movement_type', sa.Enum('COMPOUND', 'ISOLATION', name='movement_type_enum'), nullable=False),
    sa.Column('category', sa.Enum('PUSH', 'PULL', 'LEGS', 'UPPER', 'LOWER', 'FULL_BODY', 'CORE', name='exercise_category_enum'), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='exercise_difficulty_enum'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_exercises_primary_muscles', 'exercises', ['primary_muscles'], unique=False, postgresql_using='gin')
    op.create_index('ix_exercises_secondary_muscles', 'exercises', ['secondary_muscles'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex_enum'), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('goal_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activity_level_enum'), nullable=False),
    sa.Column('training_experience', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='training_experience_enum'), nullable=False),
    sa.Column('dietary_preference', sa.Enum('NONE', 'VEGETARIAN', 'VEGAN', 'PESCATARIAN', 'KETO', 'OTHER', name='dietary_preference_enum'), nullable=False),
    sa.Column('unit_weight', sa.Enum('KG', 'LB', name='weight_unit_enum'), nullable=False),
    sa.Column('unit_length', sa.Enum('CM', 'IN', name='length_unit_enum'), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_messages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='chat_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=True),
    sa.Column('tool_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('macro_targets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bmr', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('tdee', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('goal', sa.Enum('CUT', 'MAINTAIN', 'BULK', name='macro_goal_enum'), nullable=False),
    sa.Column('target_calories', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('target_protein_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('target_carbs_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('target_fat_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_targets_user_id'), 'macro_targets', ['user_id'], unique=False)
    op.create_index('uq_macro_targets_one_active_per_user', 'macro_targets', ['user_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('weight_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('logged_at', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'logged_at', name='uq_weight_logs_user_date')
    )
    op.create_index(op.f('ix_weight_logs_user_id'), 'weight_logs', ['user_id'], unique=False)
    op.create_table('workouts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workouts_user_id'), 'workouts', ['user_id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_exercise_id'), 'workout_sets', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_sets_workout_id'), 'workout_sets', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sets_workout_id'), table_name='workout_sets')
    op.drop_index(op.f('ix_workout_sets_exercise_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_workouts_user_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_weight_logs_user_id'), table_name='weight_logs')
    op.drop_table('weight_logs')
    op.drop_index('uq_macro_targets_one_active_per_user', table_name='macro_targets', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_macro_targets_user_id'), table_name='macro_targets')
    op.drop_table('macro_targets')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_exercises_secondary_muscles', table_name='exercises', postgresql_using='gin')
    op.drop_index('ix_exercises_primary_muscles', table_name='exercises', postgresql_using='gin')
    op.drop_table('exercises')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for Postgres enums on downgrade
    # (it only diffs tables/columns, not the enum types columns depend on).
    # Left unfixed, downgrade-then-upgrade fails with "type already exists"
    # the moment op.create_table tries to recreate one. Added by hand.
    for enum_name in (
        "movement_type_enum",
        "exercise_category_enum",
        "exercise_difficulty_enum",
        "sex_enum",
        "activity_level_enum",
        "training_experience_enum",
        "dietary_preference_enum",
        "weight_unit_enum",
        "length_unit_enum",
        "chat_role_enum",
        "macro_goal_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
