"""add exercise progressions and default increment

Revision ID: 24807337a960
Revises: 81c7e9d41ecc
Create Date: 2026-08-09 18:58:48.876056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24807337a960'
down_revision: Union[str, None] = '81c7e9d41ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_progressions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('increment_kg', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('next_suggested_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_exercise_progression_user_exercise')
    )
    op.create_index(op.f('ix_exercise_progressions_exercise_id'), 'exercise_progressions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_progressions_user_id'), 'exercise_progressions', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    # server_default required: existing users rows need a value for this
    # NOT NULL column at add-time. Dropped again after — the ORM's own
    # default=Decimal("2.5") already covers every future insert.
    op.add_column(
        'users',
        sa.Column(
            'default_progression_increment_kg',
            sa.Numeric(precision=4, scale=2),
            nullable=False,
            server_default=sa.text('2.5'),
        ),
    )
    op.alter_column('users', 'default_progression_increment_kg', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_progression_increment_kg')
    op.drop_index(op.f('ix_exercise_progressions_user_id'), table_name='exercise_progressions')
    op.drop_index(op.f('ix_exercise_progressions_exercise_id'), table_name='exercise_progressions')
    op.drop_table('exercise_progressions')
    # ### end Alembic commands ###
