"""add visual library media and detail fields to exercises

Revision ID: 29314511ddfb
Revises: 2a71bbb815e3
Create Date: 2026-08-07 20:50:16.850544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29314511ddfb'
down_revision: Union[str, None] = '2a71bbb815e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('exercises', sa.Column('preview_media_url', sa.String(length=500), nullable=True))
    # add_column (unlike create_table) doesn't auto-issue CREATE TYPE for an
    # inline Enum, so the type has to be created explicitly before it's
    # referenced or the ALTER TABLE fails with "type ... does not exist".
    preview_media_type_enum = postgresql.ENUM(
        'GIF', 'MP4', 'WEBM', name='exercise_preview_media_type_enum'
    )
    preview_media_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('exercises', sa.Column('preview_media_type', preview_media_type_enum, nullable=True))
    op.add_column('exercises', sa.Column('instructions', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('exercises', sa.Column('common_mistakes', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('exercises', sa.Column('breathing_tips', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('range_of_motion', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('tempo', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('recommended_sets', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('recommended_reps', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('beginner_tips', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('advanced_tips', sa.Text(), nullable=True))
    op.add_column('exercises', sa.Column('safety_notes', sa.Text(), nullable=True))
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'safety_notes')
    op.drop_column('exercises', 'advanced_tips')
    op.drop_column('exercises', 'beginner_tips')
    op.drop_column('exercises', 'recommended_reps')
    op.drop_column('exercises', 'recommended_sets')
    op.drop_column('exercises', 'tempo')
    op.drop_column('exercises', 'range_of_motion')
    op.drop_column('exercises', 'breathing_tips')
    op.drop_column('exercises', 'common_mistakes')
    op.drop_column('exercises', 'instructions')
    op.drop_column('exercises', 'preview_media_type')
    op.drop_column('exercises', 'preview_media_url')
    op.drop_column('exercises', 'thumbnail_url')
    # ### end Alembic commands ###
    # Autogenerate never emits DROP TYPE for Postgres enums (see
    # 71afbca48f94 for the same gap) — without this, re-running upgrade
    # after a downgrade fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS exercise_preview_media_type_enum")
