"""add custom_exercises and favorite_exercises tables

Revision ID: 2a71bbb815e3
Revises: 353722b9f1e2
Create Date: 2026-08-07 19:15:38.415262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a71bbb815e3'
down_revision: Union[str, None] = '353722b9f1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_exercises',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_muscles', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('secondary_muscles', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('equipment', sa.String(length=50), nullable=False),
    sa.Column('movement_type', sa.Enum('COMPOUND', 'ISOLATION', name='custom_exercise_movement_type_enum'), nullable=False),
    sa.Column('category', sa.Enum('PUSH', 'PULL', 'LEGS', 'UPPER', 'LOWER', 'FULL_BODY', 'CORE', name='custom_exercise_category_enum'), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='custom_exercise_difficulty_enum'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_custom_exercise_user_name')
    )
    op.create_index(op.f('ix_custom_exercises_user_id'), 'custom_exercises', ['user_id'], unique=False)
    op.create_table('favorite_exercises',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('custom_exercise_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(exercise_id IS NOT NULL) != (custom_exercise_id IS NOT NULL)', name='ck_favorite_exercise_exactly_one_source'),
    sa.ForeignKeyConstraint(['custom_exercise_id'], ['custom_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'custom_exercise_id', name='uq_favorite_user_custom_exercise'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_favorite_user_exercise')
    )
    op.create_index(op.f('ix_favorite_exercises_user_id'), 'favorite_exercises', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_exercises_user_id'), table_name='favorite_exercises')
    op.drop_table('favorite_exercises')
    op.drop_index(op.f('ix_custom_exercises_user_id'), table_name='custom_exercises')
    op.drop_table('custom_exercises')
    # ### end Alembic commands ###
    # Autogenerate never emits DROP TYPE for Postgres enums (see
    # 71afbca48f94 for the same gap) — without this, re-running upgrade
    # after a downgrade fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS custom_exercise_movement_type_enum")
    op.execute("DROP TYPE IF EXISTS custom_exercise_category_enum")
    op.execute("DROP TYPE IF EXISTS custom_exercise_difficulty_enum")
