"""add chat_sessions table and session_id to chat_messages

Revision ID: 5ea6d4fd94fe
Revises: b6171f2d6877
Create Date: 2026-08-07 17:32:54.114151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea6d4fd94fe'
down_revision: Union[str, None] = 'b6171f2d6877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAME = "fk_chat_messages_session_id_chat_sessions"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d): that index was
    # created via raw SQL, not a SQLAlchemy Index() construct, so autogenerate
    # can't see it in model metadata and reads it as "should be removed".
    # Left out entirely, unrelated to this migration.
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)

    # session_id starts nullable so pre-existing rows aren't rejected, gets
    # backfilled into one session per user (grouping their whole prior
    # history together, since there was no thread concept before this), then
    # locked to NOT NULL.
    op.add_column('chat_messages', sa.Column('session_id', sa.UUID(), nullable=True))
    op.execute(
        """
        INSERT INTO chat_sessions (id, user_id, title, created_at, updated_at)
        SELECT gen_random_uuid(), user_id, 'Previous conversation', MIN(created_at), MAX(created_at)
        FROM chat_messages
        GROUP BY user_id
        """
    )
    op.execute(
        """
        UPDATE chat_messages cm
        SET session_id = cs.id
        FROM chat_sessions cs
        WHERE cm.user_id = cs.user_id
        """
    )
    op.alter_column('chat_messages', 'session_id', existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_foreign_key(FK_NAME, 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_NAME, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'session_id')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
