"""add generated_splits and split_day_completions tables

Revision ID: 71afbca48f94
Revises: f3b4ce11b9fa
Create Date: 2026-08-07 18:19:46.895229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71afbca48f94'
down_revision: Union[str, None] = 'f3b4ce11b9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_splits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('split_type', sa.String(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='split_experience_level_enum'), nullable=False),
    sa.Column('goal', sa.Enum('STRENGTH', 'HYPERTROPHY', 'GENERAL_FITNESS', name='training_goal_enum'), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_splits_user_id'), 'generated_splits', ['user_id'], unique=False)
    op.create_index('uq_generated_splits_one_active_per_user', 'generated_splits', ['user_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('split_day_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['generated_splits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_split_day_completions_split_id'), 'split_day_completions', ['split_id'], unique=False)
    op.create_index(op.f('ix_split_day_completions_user_id'), 'split_day_completions', ['user_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_split_day_completions_user_id'), table_name='split_day_completions')
    op.drop_index(op.f('ix_split_day_completions_split_id'), table_name='split_day_completions')
    op.drop_table('split_day_completions')
    op.drop_index('uq_generated_splits_one_active_per_user', table_name='generated_splits', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_generated_splits_user_id'), table_name='generated_splits')
    op.drop_table('generated_splits')
    # ### end Alembic commands ###
    # Autogenerate never emits DROP TYPE for Postgres enums (a known gap,
    # same one noted for other enum columns in this project) — without
    # this, re-running upgrade after a downgrade fails with "type already
    # exists" since op.drop_table() doesn't remove the enum types it used.
    op.execute("DROP TYPE IF EXISTS split_experience_level_enum")
    op.execute("DROP TYPE IF EXISTS training_goal_enum")
