"""add remember_me to refresh_tokens

Revision ID: 81c7e9d41ecc
Revises: c8891c4e875d
Create Date: 2026-08-09 18:04:12.571271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c7e9d41ecc'
down_revision: Union[str, None] = 'c8891c4e875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    # server_default is required here (not just the model's default=True):
    # existing refresh_tokens rows need a value for this NOT NULL column at
    # add-time. Dropped again below so it doesn't linger as a schema-level
    # default beyond this migration — the ORM's default=True already covers
    # every future insert.
    op.add_column(
        'refresh_tokens',
        sa.Column('remember_me', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.alter_column('refresh_tokens', 'remember_me', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'remember_me')
    # Same ix_exercises_embedding_hnsw false positive as upgrade(), mirrored
    # on the downgrade side — left out entirely, same as every other
    # migration in this repo.
    # ### end Alembic commands ###
