"""add username, avatar_url, firebase_uid to users; hashed_password nullable

Revision ID: 8fe091f66363
Revises: da74ebb6ec5d
Create Date: 2026-08-07 08:47:00.432620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe091f66363'
down_revision: Union[str, None] = 'da74ebb6ec5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here — a known false positive (see da74ebb6ec5d): that index was
    # created via raw SQL, not a SQLAlchemy Index() construct, so autogenerate
    # can't see it in model metadata and reads it as "should be removed".
    # Left out entirely; unrelated to this migration.
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=128), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # Backfill pre-existing rows (username didn't exist before this
    # migration) with a placeholder derived from their id, guaranteed
    # unique since id is the primary key — real users can change it via
    # the profile page afterward.
    # 'u_' + 28 hex chars = 30, exactly the column's max length.
    op.execute("UPDATE users SET username = 'u_' || substr(replace(id::text, '-', ''), 1, 28) WHERE username IS NULL")
    op.alter_column('users', 'username', existing_type=sa.String(length=30), nullable=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'firebase_uid')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
