"""add custom exercise support and duration to workouts

Revision ID: c8891c4e875d
Revises: 1292668f3937
Create Date: 2026-08-09 18:00:07.195781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8891c4e875d'
down_revision: Union[str, None] = '1292668f3937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    op.add_column('workout_sets', sa.Column('custom_exercise_id', sa.UUID(), nullable=True))
    op.alter_column('workout_sets', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_workout_sets_custom_exercise_id'), 'workout_sets', ['custom_exercise_id'], unique=False)
    op.create_foreign_key(
        'fk_workout_sets_custom_exercise_id', 'workout_sets', 'custom_exercises', ['custom_exercise_id'], ['id']
    )
    op.add_column('workouts', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate never detects CheckConstraint changes — added by hand,
    # matching the exact pattern favorite_exercises already uses.
    op.create_check_constraint(
        'ck_workout_set_exactly_one_source',
        'workout_sets',
        '(exercise_id IS NOT NULL) != (custom_exercise_id IS NOT NULL)',
    )


def downgrade() -> None:
    op.drop_constraint('ck_workout_set_exactly_one_source', 'workout_sets', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'duration_seconds')
    op.drop_constraint('fk_workout_sets_custom_exercise_id', 'workout_sets', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sets_custom_exercise_id'), table_name='workout_sets')
    op.alter_column('workout_sets', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workout_sets', 'custom_exercise_id')
    # ### end Alembic commands ###
