"""add pgvector embeddings

Revision ID: cf99115b312e
Revises: 23cccd36656a
Create Date: 2026-08-06 17:42:07.742600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cf99115b312e'
down_revision: Union[str, None] = '23cccd36656a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Must exist before any column/table below can use the vector type.
    # postgres/pgvector:pg16 ships the extension but doesn't enable it by
    # default in a fresh database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_summaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_summaries_user_id'), 'chat_summaries', ['user_id'], unique=False)
    op.add_column('exercises', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###

    # HNSW: pgvector's modern index type — unlike IVFFlat it needs no
    # list-count tuned to table size and gives better recall. Cosine
    # distance since embeddings are L2-normalized (see app/services/embeddings.py).
    op.execute(
        "CREATE INDEX ix_exercises_embedding_hnsw ON exercises "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_exercises_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'embedding')
    op.drop_index(op.f('ix_chat_summaries_user_id'), table_name='chat_summaries')
    op.drop_table('chat_summaries')
    # ### end Alembic commands ###

    # Only safe because this migration is also the one that created the
    # extension — dropping it here would break any other table still
    # depending on the vector type if one existed.
    op.execute("DROP EXTENSION IF EXISTS vector")
