"""add onboarding_completed_at to users

Revision ID: f3b4ce11b9fa
Revises: 5ea6d4fd94fe
Create Date: 2026-08-07 18:11:32.523334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b4ce11b9fa'
down_revision: Union[str, None] = '5ea6d4fd94fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed dropping ix_exercises_embedding_hnsw
    # here, a known false positive (see da74ebb6ec5d) — left out entirely.
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_at')
    # ### end Alembic commands ###
