import type { AccentColor } from "../store/themeStore";

/** Branding assets generated by scripts/generate-branding.mjs from the
 * master PNGs (public/favicon-purple.png, public/favicon-emerald.png) —
 * see public/branding/ for the full icon set (SVG logo marks, apple-touch
 * icon, android-chrome icons, favicon.ico, site.webmanifest). */
const FAVICON_BY_ACCENT: Record<AccentColor, string> = {
  violet: "/branding/favicon-purple.png",
  emerald: "/branding/favicon-green.png",
};

const THEME_COLOR_BY_ACCENT: Record<AccentColor, string> = {
  violet: "#7b32fb",
  emerald: "#0da06a",
};

const FAVICON_LINK_ID = "favicon";
const THEME_COLOR_META_ID = "theme-color-meta";

/** Swaps the browser tab favicon and the theme-color meta tag to match the
 * given accent. Called from themeStore's applyToDocument() — the same
 * single hook point that already applies data-theme/data-accent to <html>
 * — so this reuses the existing theme state instead of tracking its own.
 *
 * Updates the existing <link>/<meta> elements from index.html in place
 * (by id) rather than creating new ones: swapping an element's href/content
 * is enough to make the browser refetch and repaint the tab icon
 * immediately, no full page reload needed, and no cache-busting query
 * param is necessary since the two accent values are already distinct URLs
 * (there's nothing stale to bust between them). apple-touch-icon and the
 * webmanifest icons are NOT touched here — see README note below.
 */
export function applyFaviconTheme(accentColor: AccentColor): void {
  if (typeof document === "undefined") return;

  const link = document.getElementById(FAVICON_LINK_ID) as HTMLLinkElement | null;
  if (link) {
    link.href = FAVICON_BY_ACCENT[accentColor];
  }

  const themeColorMeta = document.getElementById(THEME_COLOR_META_ID) as HTMLMetaElement | null;
  if (themeColorMeta) {
    themeColorMeta.content = THEME_COLOR_BY_ACCENT[accentColor];
  }
}

// Platform limitation, not fixable from JS: apple-touch-icon (iOS home
// screen), android-chrome-192/512 (Android home screen / PWA), and
// favicon.ico (legacy browser fallback) are read once by the OS or browser
// chrome outside the page's lifecycle, not the live DOM, so they can't
// react to a theme change without the user re-adding/reinstalling the
// icon. They stay fixed at the default (violet/purple) — see
// public/branding/site.webmanifest and index.html.
